User interactions
emmanuelcortes2/MyCapstone pull request #6
Opened 2022-11-24 13:42 UTC by emmanuelcortes2

## Interactions

- Added adaptative menus
- Added graphics & styling
- Added speakers section to work dynamically
- Added Readme & video presentation

2022-11-24 15:53 UTC, Olamarx requested changes
Hi @emmanuelcortes2,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>
## Highlights
- All linters passed ✅
- Home and About pages ✅

## Required Changes ♻️
_Check the comments under the review._
### Note, I would have made these comments inline but they seem not to be on the file changes.

- [ ] Kindly use the latest readme file as it has more details. You can find it [here](https://github.com/microverseinc/readme-template)
- [ ] Kindly align the topbar to the right as it is on Behance.
### Your design
![image](https://user-images.githubusercontent.com/86200356/203823996-3bc45753-2f35-49cb-ba2a-c16b5e9c1c94.png)
### Behance 
![image](https://user-images.githubusercontent.com/86200356/203824117-f7e4a854-9a0d-449a-8299-d86b0510a039.png)
- [ ] When I click on more on the home mobile version, it goes to the about section, I think the functionality for the more is to be revisited.
![image](https://user-images.githubusercontent.com/86200356/203824540-23a95d39-e6d4-4fd5-87d5-ccbab16b0c61.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 15:53 UTC, Olamarx commented on README.md
> +-Behance: [@Adagio07](https://www.behance.net/adagio07)
- [ ] This acknowledgment should be under the acknowledgment section in this readme file.

2022-11-24 15:53 UTC, Olamarx commented on README.md
> +- etc
This is the acknowledgment section that I am talking about.

2022-11-24 15:53 UTC, Olamarx commented on styles.css
>  }
- [ ] This footer should have a white background on the about page. It should have white on the home page which it actually has but for the footer, you can achieve it by adding another class name and styling that class to have the background color you need.

2022-11-24 15:53 UTC, Olamarx commented on index.html
>                      <img class="icon" src="./images/calendar_days_icon.svg" width="50px" alt="">
- [ ] Kindly add alt to all the images so that other devices can access your site, devices like screen readers.

2022-11-25 00:59 UTC, Owusu-Desmond approved these changes
Hi @emmanuelcortes2 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/92303891/203880163-d849e794-e6a0-4baa-bfdc-679d3c79130f.png)


## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2026-02-25 15:10 UTC, merged